In [1]:
import os
os.chdir("../../")#与easymlops同级目录

### 拆分数据

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [4]:
from easymlops import TablePipeLine
from easymlops.table.encoding import *
from easymlops.table.preprocessing import *
from easymlops.table.decomposition import *

In [5]:
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(FillNa())\
  .pipe(OneHotEncoding(cols=["Pclass","Sex"],drop_col=False))\
  .pipe(LabelEncoding(cols=["Sex","Pclass"]))\
  .pipe(TargetEncoding(cols=["Name","Ticket","Embarked","Cabin"],y=y_train))\
  .pipe(PCADecomposition(n_components=4))

x_test_new=table.fit(x_train).transform(x_test)
x_test_new.head(5)

              0          1          2         3
500  250.112431 -27.094711  -5.835574 -0.250618
501  251.117575 -27.778216  -1.808170 -0.265342
502  252.017783 -29.145885 -22.761863 -0.698056
503  253.218449 -25.038811  14.050332  0.200772
504  255.219670  50.502969 -11.396099 -1.079058

### 性能、一致性测试

In [ ]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.3ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.OneHotEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.LabelEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.TargetEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.decomposition.tradition.PCADecomposition'>) module check [transform] complete,speed:[6.16ms]/it,cpu:[41%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[5.83ms]/it,cpu:[41%],memory:[24K]
column:[Pclass] check [null value] complete,speed:[5.54ms]/it,cpu:[25%],memory:[0K]
column:[Name] check [null value] complete,speed:[6.08ms]/it,cpu:[36%],memory:[708K]
column:[Sex] check [null value] complete,speed:[5.99ms]/it,cpu:[28%],memory:[0K]
column:[Age] check [null value] complete,speed:[6.09ms]/it,cpu:[25%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[5.89ms]/it,cpu:[44%],memory:[0K]
column:[Parch] check [null value] complete,speed:[5.72ms]/it,cpu:[26%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[5.88ms]/it,cpu:[33%],memory:[0K]
column:[Fare] check [null value] complete,speed:[6.41ms]/it,cpu:[29%],memory:[40K]
column:[Cabin] check [null value] complete,speed:[6.24ms]/it,cpu:[29%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[6.35ms]/it,cpu:[33%],memory:[12K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[6.27ms]/it,cpu:[43%],memory:[13984K]
column:[Pclass] check [extreme value] complete,speed:[13.87ms]/it,cpu:[94%],memory:[87964K]
column:[Name] check [extreme value] complete,speed:[6.95ms]/it,cpu:[72%],memory:[28688K]
column:[Sex] check [extreme value] complete,speed:[6.57ms]/it,cpu:[45%],memory:[50136K]
column:[Age] check [extreme value] complete,speed:[5.85ms]/it,cpu:[46%],memory:[14552K]
column:[SibSp] check [extreme value] complete,speed:[5.85ms]/it,cpu:[41%],memory:[8288K]
column:[Parch] check [extreme value] complete,speed:[5.88ms]/it,cpu:[38%],memory:[2988K]
column:[Ticket] check [extreme value] complete,speed:[6.05ms]/it,cpu:[37%],memory:[2444K]
column:[Fare] check [extreme value] complete,speed:[5.79ms]/it,cpu:[35%],memory:[2412K]
column:[Cabin] check [extreme value] complete,speed:[5.87ms]/it,cpu:[34%],memory:[5956K]
column:[Embarked] check [extreme value] complete,speed:[5.66ms]/it,cpu:[33%],memory:[11640K]
column:[__all__] check [extreme value] complete,speed:[6.06ms]/it,cpu:[47%],memory:[5232K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[5.83ms]/it,cpu:[33%],memory:[1968K]

### 持久化测试

In [7]:
table.save("ml.pkl")

In [8]:
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(FillNa())\
  .pipe(OneHotEncoding(cols=["Pclass","Sex"],drop_col=False))\
  .pipe(LabelEncoding(cols=["Sex","Pclass"]))\
  .pipe(TargetEncoding(cols=["Name","Ticket","Embarked","Cabin"]))\
  .pipe(PCADecomposition(n_components=4))

table.load("ml.pkl")

In [9]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.3ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.OneHotEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.LabelEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.TargetEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.decomposition.tradition.PCADecomposition'>) module check [transform] complete,speed:[7.76ms]/it,cpu:[37%],memory:[20K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[6.18ms]/it,cpu:[15%],memory:[56K]
column:[Pclass] check [null value] complete,speed:[5.53ms]/it,cpu:[18%],memory:[0K]
column:[Name] check [null value] complete,speed:[7.33ms]/it,cpu:[12%],memory:[0K]
column:[Sex] check [null value] complete,speed:[5.98ms]/it,cpu:[15%],memory:[0K]
column:[Age] check [null value] complete,speed:[9.52ms]/it,cpu:[33%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[6.51ms]/it,cpu:[31%],memory:[244K]
column:[Parch] check [null value] complete,speed:[5.7ms]/it,cpu:[12%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[5.6ms]/it,cpu:[20%],memory:[0K]
column:[Fare] check [null value] complete,speed:[5.54ms]/it,cpu:[34%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[6.35ms]/it,cpu:[46%],memory:[824K]
column:[Embarked] check [null value] complete,speed:[6.16ms]/it,cpu:[18%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[5.84ms]/it,cpu:[25%],memory:[452K]
column:[Pclass] check [extreme value] complete,speed:[5.97ms]/it,cpu:[33%],memory:[3272K]
column:[Name] check [extreme value] complete,speed:[5.06ms]/it,cpu:[22%],memory:[8928K]
column:[Sex] check [extreme value] complete,speed:[5.6ms]/it,cpu:[40%],memory:[4508K]
column:[Age] check [extreme value] complete,speed:[5.45ms]/it,cpu:[34%],memory:[1228K]
column:[SibSp] check [extreme value] complete,speed:[5.32ms]/it,cpu:[20%],memory:[2432K]
column:[Parch] check [extreme value] complete,speed:[5.2ms]/it,cpu:[41%],memory:[6656K]
column:[Ticket] check [extreme value] complete,speed:[5.42ms]/it,cpu:[37%],memory:[3428K]
column:[Fare] check [extreme value] complete,speed:[5.67ms]/it,cpu:[22%],memory:[2256K]
column:[Cabin] check [extreme value] complete,speed:[5.58ms]/it,cpu:[25%],memory:[1204K]
column:[Embarked] check [extreme value] complete,speed:[5.94ms]/it,cpu:[59%],memory:[1084K]
column:[__all__] check [extreme value] complete,speed:[5.51ms]/it,cpu:[35%],memory:[8504K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[5.45ms]/it,cpu:[31%],memory:[152K]
column:[Pclass] check [inverse type] complete,speed:[5.86ms]/it,cpu:[31%],memory:[2888K]
column:[Name] check [inverse type] complete,speed:[5.26ms]/it,cpu:[28%],memory:[972K]
column:[Sex] check [inverse type] complete,speed:[5.39ms]/it,cpu:[37%],memory:[2308K]
column:[Age] check [inverse type] complete,speed:[5.61ms]/it,cpu:[16%],memory:[1048K]
column:[SibSp] check [inverse type] complete,speed:[5.86ms]/it,cpu:[41%],memory:[3772K]
column:[Parch] check [inverse type] complete,speed:[6.21ms]/it,cpu:[60%],memory:[3644K]
column:[Ticket] check [inverse type] complete,speed:[4.97ms]/it,cpu:[50%],memory:[5368K]
column:[Fare] check [inverse type] complete,speed:[6.34ms]/it,cpu:[55%],memory:[1556K]
column:[Cabin] check [inverse type] complete,speed:[5.55ms]/it,cpu:[53%],memory:[616K]
column:[Embarked] check [inverse type] complete,speed:[5.71ms]/it,cpu:[46%],memory:[1196K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[6.27ms]/it,cpu:[12%],memory:[8K]
column:[Pclass] check [int trans float] complete,speed:[6.17ms]/it,cpu:[21%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[5.91ms]/it,cpu:[27%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[5.74ms]/it,cpu:[21%],memory:[0K]

In [10]:
table.transform(x_test[:5])

              0          1          2         3
500  250.112431 -27.094711  -5.835574 -0.250618
501  251.117575 -27.778216  -1.808170 -0.265342
502  252.017783 -29.145885 -22.761863 -0.698056
503  253.218449 -25.038811  14.050332  0.200772
504  255.219670  50.502969 -11.396099 -1.079058

In [11]:
x_test_new.head(5)

              0          1          2         3
500  250.112431 -27.094711  -5.835574 -0.250618
501  251.117575 -27.778216  -1.808170 -0.265342
502  252.017783 -29.145885 -22.761863 -0.698056
503  253.218449 -25.038811  14.050332  0.200772
504  255.219670  50.502969 -11.396099 -1.079058