In [1]:
import os
os.chdir("../../")#与easymlops同级目录

### 拆分数据

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [4]:
from easymlops import TablePipeLine
from easymlops.table.preprocessing import *
from easymlops.table.encoding import *
from easymlops.table.classification import *

In [5]:
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(FillNa())\
  .pipe(OneHotEncoding(cols=["Pclass", "Sex"], drop_col=False)) \
  .pipe(WOEEncoding(cols=["Ticket", "Embarked", "Cabin", "Sex", "Pclass"], y=y_train)) \
  .pipe(LabelEncoding(cols=["Name"]))\
  .pipe(LGBMClassification(y=y_train.map({0:"死亡",1:"存活"}),native_init_params={"max_depth":2},native_fit_params={"num_boost_round":128},drop_input_data=False))

x_test_new=table.fit(x_train).transform(x_test)
x_test_new.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_3,Pclass_1,Pclass_2,Sex_male,Sex_female,死亡,存活
500,501,0.482439,0,1.111379,17.0,0,0,0.0,8.664062,0.299607,0.224849,1,0,0,1,0,0.923326,0.076674
501,502,0.482439,0,-1.569990,21.0,0,0,0.0,7.750000,0.299607,-0.508609,1,0,0,0,1,0.373652,0.626348
502,503,0.482439,0,-1.569990,0.0,0,0,0.0,7.628906,0.299607,-0.508609,1,0,0,0,1,0.378380,0.621620
503,504,0.482439,0,-1.569990,37.0,0,0,0.0,9.585938,0.299607,0.224849,1,0,0,0,1,0.670166,0.329834
504,505,-0.741789,0,-1.569990,16.0,0,0,0.0,86.500000,0.000000,0.224849,0,1,0,0,1,0.068470,0.931530

In [6]:
# table=TablePipeLine()
# table.pipe(FixInput())\
#   .pipe(FillNa())\
#   .pipe(OneHotEncoding(cols=["Pclass", "Sex"], drop_col=False)) \
#   .pipe(WOEEncoding(cols=["Ticket", "Embarked", "Cabin", "Sex", "Pclass"], y=y_train)) \
#   .pipe(LabelEncoding(cols=["Name"]))\
#   .pipe(LGBMClassification(y=y_train.map({0:"死亡",1:"存活"}),native_init_params={"max_depth":2},native_fit_params={"num_boost_round":128}))

# x_test_new=table.fit(x_train).transform(x_test)
# x_test_new.head(5)

In [7]:
#获取sabass特征重要性
table[-1].get_contrib(table.transform_single(x_test.to_dict("record")[0],run_to_layer=-2))

{0: {'Sex': 0.5461501854144144,
  'Cabin': 0.1270063345547848,
  'Age': -0.05115085845832483,
  'Fare': 0.1265214828241528,
  'SibSp': -0.0441638895513395,
  'Ticket': 0.005658456561668252,
  'PassengerId': 0.2263838236137358,
  'Pclass_2': 0.016025418181148575},
 1: {'Sex': -0.5461501854144144,
  'Cabin': -0.1270063345547848,
  'Age': 0.05115085845832483,
  'Fare': -0.1265214828241528,
  'SibSp': 0.0441638895513395,
  'Ticket': -0.005658456561668252,
  'PassengerId': -0.2263838236137358,
  'Pclass_2': -0.016025418181148575}}

### 性能、一致性测试

In [ ]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.43ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.OneHotEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.WOEEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.LabelEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.classification.LGBMClassification'>) module check [transform] complete,speed:[4.69ms]/it,cpu:[100%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[6.49ms]/it,cpu:[91%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[7.44ms]/it,cpu:[93%],memory:[112K]
column:[Name] check [null value] complete,speed:[7.86ms]/it,cpu:[89%],memory:[0K]
column:[Sex] check [null value] complete,speed:[7.54ms]/it,cpu:[92%],memory:[8K]
column:[Age] check [null value] complete,speed:[6.6ms]/it,cpu:[85%],memory:[48K]
column:[SibSp] check [null value] complete,speed:[7.94ms]/it,cpu:[100%],memory:[0K]

### 持久化测试

In [9]:
table.save("ml.pkl")

In [10]:
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(FillNa())\
  .pipe(OneHotEncoding(cols=["Pclass", "Sex"], drop_col=False)) \
  .pipe(WOEEncoding(cols=["Ticket", "Embarked", "Cabin", "Sex", "Pclass"])) \
  .pipe(LabelEncoding(cols=["Name"]))\
  .pipe(LGBMClassification(native_init_params={"max_depth":2},native_fit_params={"num_boost_round":128}))

table.load("ml.pkl")

In [11]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.OneHotEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.WOEEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.encoding.LabelEncoding'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.classification.LGBMClassification'>) module check [transform] complete,speed:[4.69ms]/it,cpu:[84%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[6.92ms]/it,cpu:[93%],memory:[44K]
column:[Pclass] check [null value] complete,speed:[7.04ms]/it,cpu:[100%],memory:[0K]
column:[Name] check [null value] complete,speed:[7.36ms]/it,cpu:[70%],memory:[0K]
column:[Sex] check [null value] complete,speed:[7.31ms]/it,cpu:[100%],memory:[0K]
column:[Age] check [null value] complete,speed:[6.64ms]/it,cpu:[87%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[6.95ms]/it,cpu:[100%],memory:[0K]
column:[Parch] check [null value] complete,speed:[7.23ms]/it,cpu:[94%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[7.32ms]/it,cpu:[100%],memory:[0K]
column:[Fare] check [null value] complete,speed:[6.93ms]/it,cpu:[91%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[7.47ms]/it,cpu:[100%],memory:[340K]
column:[Embarked] check [null value] complete,speed:[7.31ms]/it,cpu:[87%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[7.06ms]/it,cpu:[100%],memory:[528K]
column:[Pclass] check [extreme value] complete,speed:[7.44ms]/it,cpu:[100%],memory:[232K]
column:[Name] check [extreme value] complete,speed:[7.38ms]/it,cpu:[100%],memory:[324K]
column:[Sex] check [extreme value] complete,speed:[7.17ms]/it,cpu:[100%],memory:[260K]
column:[Age] check [extreme value] complete,speed:[7.07ms]/it,cpu:[100%],memory:[452K]
column:[SibSp] check [extreme value] complete,speed:[7.59ms]/it,cpu:[100%],memory:[668K]
column:[Parch] check [extreme value] complete,speed:[8.13ms]/it,cpu:[100%],memory:[636K]
column:[Ticket] check [extreme value] complete,speed:[7.06ms]/it,cpu:[100%],memory:[3608K]
column:[Fare] check [extreme value] complete,speed:[7.61ms]/it,cpu:[100%],memory:[676K]
column:[Cabin] check [extreme value] complete,speed:[7.8ms]/it,cpu:[100%],memory:[332K]
column:[Embarked] check [extreme value] complete,speed:[7.25ms]/it,cpu:[100%],memory:[172K]
column:[__all__] check [extreme value] complete,speed:[4.62ms]/it,cpu:[100%],memory:[13562004K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[6.95ms]/it,cpu:[100%],memory:[480K]
column:[Pclass] check [inverse type] complete,speed:[7.83ms]/it,cpu:[100%],memory:[1992K]
column:[Name] check [inverse type] complete,speed:[7.42ms]/it,cpu:[100%],memory:[5892K]
column:[Sex] check [inverse type] complete,speed:[7.44ms]/it,cpu:[100%],memory:[936K]
column:[Age] check [inverse type] complete,speed:[7.47ms]/it,cpu:[100%],memory:[152K]
column:[SibSp] check [inverse type] complete,speed:[7.26ms]/it,cpu:[100%],memory:[292K]
column:[Parch] check [inverse type] complete,speed:[7.49ms]/it,cpu:[100%],memory:[220K]
column:[Ticket] check [inverse type] complete,speed:[7.55ms]/it,cpu:[100%],memory:[280K]
column:[Fare] check [inverse type] complete,speed:[7.26ms]/it,cpu:[100%],memory:[288K]
column:[Cabin] check [inverse type] complete,speed:[7.31ms]/it,cpu:[100%],memory:[252K]
column:[Embarked] check [inverse type] complete,speed:[7.54ms]/it,cpu:[100%],memory:[184K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[7.77ms]/it,cpu:[87%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[6.25ms]/it,cpu:[100%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[6.25ms]/it,cpu:[85%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[7.81ms]/it,cpu:[100%],memory:[0K]

In [12]:
table.transform(x_test[:5])

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_3,Pclass_1,Pclass_2,Sex_male,Sex_female,死亡,存活
500,501,0.482439,0,1.111379,17.0,0,0,0.0,8.664062,0.299607,0.224849,1,0,0,1,0,0.923326,0.076674
501,502,0.482439,0,-1.569990,21.0,0,0,0.0,7.750000,0.299607,-0.508609,1,0,0,0,1,0.373652,0.626348
502,503,0.482439,0,-1.569990,0.0,0,0,0.0,7.628906,0.299607,-0.508609,1,0,0,0,1,0.378380,0.621620
503,504,0.482439,0,-1.569990,37.0,0,0,0.0,9.585938,0.299607,0.224849,1,0,0,0,1,0.670166,0.329834
504,505,-0.741789,0,-1.569990,16.0,0,0,0.0,86.500000,0.000000,0.224849,0,1,0,0,1,0.068470,0.931530

In [13]:
x_test_new.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_3,Pclass_1,Pclass_2,Sex_male,Sex_female,死亡,存活
500,501,0.482439,0,1.111379,17.0,0,0,0.0,8.664062,0.299607,0.224849,1,0,0,1,0,0.923326,0.076674
501,502,0.482439,0,-1.569990,21.0,0,0,0.0,7.750000,0.299607,-0.508609,1,0,0,0,1,0.373652,0.626348
502,503,0.482439,0,-1.569990,0.0,0,0,0.0,7.628906,0.299607,-0.508609,1,0,0,0,1,0.378380,0.621620
503,504,0.482439,0,-1.569990,37.0,0,0,0.0,9.585938,0.299607,0.224849,1,0,0,0,1,0.670166,0.329834
504,505,-0.741789,0,-1.569990,16.0,0,0,0.0,86.500000,0.000000,0.224849,0,1,0,0,1,0.068470,0.931530