In [1]:
import os
os.chdir("../../")#与easymlops同级目录

In [2]:
import numpy
numpy.__version__

'1.24.4'

In [3]:
import gensim
gensim.__version__

'4.3.0'

### 拆分数据

In [4]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [6]:
from easymlops import NLPPipeline
from easymlops.table.preprocessing import *
from easymlops.table.ensemble import *
from easymlops.nlp.preprocessing import *
from easymlops.nlp.representation import *
from easymlops.table.perfopt import *

In [7]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa(cols=["Name","Age"]))\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(ReplacePunctuation(cols=["Name"],symbols=""))\
   .pipe(SelectCols(cols=["Age","Name"]))\
   .pipe(Parallel([LsiTopicModel(cols=["Name"],num_topics=4),Word2VecModel(embedding_size=4,cols=["Name"])]))\
   .pipe(DropCols(cols=["Name"]))

x_test_new=nlp.fit(x_train).transform(x_test)
x_test_new.head(5)

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,0.006943,-0.049788,0.094199,-0.016030,0.003412,0.131879,0.227311
501,0.001774,-1.027363,-0.072602,0.017521,-0.168437,-0.080284,0.188844,0.057639
502,0.001778,-1.035647,-0.074126,0.017324,-0.168437,-0.080284,0.188844,0.057639
503,0.001211,-0.985805,-0.123092,-0.009465,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,-0.968351,-0.120909,-0.007717,-0.233626,-0.181061,0.165193,0.226518

### 性能、一致性测试

In [8]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.3ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ReplacePunctuation'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[3.01ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.DropCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[3.53ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[3.53ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [null value] complete,speed:[3.47ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[3.56ms]/it,cpu:[42%],memory:[0K]
column:[Age] check [null value] complete,speed:[3.69ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[3.63ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [null value] complete,speed:[3.96ms]/it,cpu:[57%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[3.59ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[3.49ms]/it,cpu:[48%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[3.65ms]/it,cpu:[37%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[3.85ms]/it,cpu:[45%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[3.36ms]/it,cpu:[45%],memory:[13788668K]
column:[Pclass] check [extreme value] complete,speed:[3.58ms]/it,cpu:[54%],memory:[13789248K]
column:[Name] check [extreme value] complete,speed:[3.71ms]/it,cpu:[40%],memory:[13789280K]
column:[Sex] check [extreme value] complete,speed:[3.54ms]/it,cpu:[50%],memory:[13788740K]
column:[Age] check [extreme value] complete,speed:[3.8ms]/it,cpu:[46%],memory:[13789320K]
column:[SibSp] check [extreme value] complete,speed:[3.62ms]/it,cpu:[50%],memory:[13788592K]
column:[Parch] check [extreme value] complete,speed:[3.45ms]/it,cpu:[41%],memory:[13788468K]
column:[Ticket] check [extreme value] complete,speed:[3.55ms]/it,cpu:[43%],memory:[13788652K]
column:[Fare] check [extreme value] complete,speed:[3.51ms]/it,cpu:[56%],memory:[13788768K]
column:[Cabin] check [extreme value] complete,speed:[3.64ms]/it,cpu:[40%],memory:[13788520K]
column:[Embarked] check [extreme value] complete,speed:[3.99ms]/it,cpu:[70%],memory:[13787460K]
column:[__all__] check [extreme value] complete,speed:[3.81ms]/it,cpu:[50%],memory:[13787328K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[3.7ms]/it,cpu:[45%],memory:[13787192K]
column:[Pclass] check [inverse type] complete,speed:[3.77ms]/it,cpu:[65%],memory:[13786904K]
column:[Name] check [inverse type] complete,speed:[3.81ms]/it,cpu:[58%],memory:[13787216K]
column:[Sex] check [inverse type] complete,speed:[3.61ms]/it,cpu:[40%],memory:[13787252K]
column:[Age] check [inverse type] complete,speed:[4.15ms]/it,cpu:[66%],memory:[13787172K]
column:[SibSp] check [inverse type] complete,speed:[3.96ms]/it,cpu:[56%],memory:[3032K]
column:[Parch] check [inverse type] complete,speed:[3.7ms]/it,cpu:[70%],memory:[13784264K]
column:[Ticket] check [inverse type] complete,speed:[3.34ms]/it,cpu:[54%],memory:[13787512K]
column:[Fare] check [inverse type] complete,speed:[3.83ms]/it,cpu:[59%],memory:[13787276K]
column:[Cabin] check [inverse type] complete,speed:[3.74ms]/it,cpu:[54%],memory:[13787476K]
column:[Embarked] check [inverse type] complete,speed:[3.84ms]/it,cpu:[53%],memory:[13786964K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[4.71ms]/it,cpu:[50%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[3.24ms]/it,cpu:[42%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[3.02ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[3.59ms]/it,cpu:[0%],memory:[0K]

### 持久化测试

In [9]:
nlp.save("ml.pkl")

In [10]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa(cols=["Name","Age"]))\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(ReplacePunctuation(cols=["Name"],symbols=""))\
   .pipe(SelectCols(cols=["Age","Name"]))\
   .pipe(Parallel([LsiTopicModel(cols=["Name"],num_topics=4),Word2VecModel(embedding_size=4,cols=["Name"])]))\
   .pipe(DropCols(cols=["Name"]))

nlp.load("ml.pkl")

In [11]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.41ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ReplacePunctuation'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[2.82ms]/it,cpu:[37%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.DropCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[3.61ms]/it,cpu:[33%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[3.51ms]/it,cpu:[37%],memory:[0K]
column:[Name] check [null value] complete,speed:[3.57ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[3.99ms]/it,cpu:[0%],memory:[0K]
column:[Age] check [null value] complete,speed:[3.95ms]/it,cpu:[65%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[3.85ms]/it,cpu:[54%],memory:[0K]
column:[Parch] check [null value] complete,speed:[3.82ms]/it,cpu:[37%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[3.56ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[3.95ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[3.95ms]/it,cpu:[45%],memory:[20K]
column:[Embarked] check [null value] complete,speed:[3.6ms]/it,cpu:[0%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[3.82ms]/it,cpu:[60%],memory:[13817844K]
column:[Pclass] check [extreme value] complete,speed:[3.23ms]/it,cpu:[60%],memory:[13815288K]
column:[Name] check [extreme value] complete,speed:[3.69ms]/it,cpu:[44%],memory:[13815192K]
column:[Sex] check [extreme value] complete,speed:[3.52ms]/it,cpu:[64%],memory:[13815364K]
column:[Age] check [extreme value] complete,speed:[3.72ms]/it,cpu:[60%],memory:[13812064K]
column:[SibSp] check [extreme value] complete,speed:[3.57ms]/it,cpu:[76%],memory:[13813764K]
column:[Parch] check [extreme value] complete,speed:[3.7ms]/it,cpu:[50%],memory:[13813716K]
column:[Ticket] check [extreme value] complete,speed:[3.6ms]/it,cpu:[50%],memory:[13813632K]
column:[Fare] check [extreme value] complete,speed:[3.26ms]/it,cpu:[45%],memory:[13811512K]
column:[Cabin] check [extreme value] complete,speed:[3.75ms]/it,cpu:[46%],memory:[13811140K]
column:[Embarked] check [extreme value] complete,speed:[3.47ms]/it,cpu:[50%],memory:[13811000K]
column:[__all__] check [extreme value] complete,speed:[3.63ms]/it,cpu:[58%],memory:[13810556K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[3.57ms]/it,cpu:[61%],memory:[13809548K]
column:[Pclass] check [inverse type] complete,speed:[3.43ms]/it,cpu:[44%],memory:[13810064K]
column:[Name] check [inverse type] complete,speed:[3.67ms]/it,cpu:[44%],memory:[13809928K]
column:[Sex] check [inverse type] complete,speed:[3.42ms]/it,cpu:[45%],memory:[13809752K]
column:[Age] check [inverse type] complete,speed:[3.46ms]/it,cpu:[37%],memory:[13809496K]
column:[SibSp] check [inverse type] complete,speed:[3.57ms]/it,cpu:[43%],memory:[13809832K]
column:[Parch] check [inverse type] complete,speed:[3.34ms]/it,cpu:[45%],memory:[13809616K]
column:[Ticket] check [inverse type] complete,speed:[3.73ms]/it,cpu:[56%],memory:[13809352K]
column:[Fare] check [inverse type] complete,speed:[3.46ms]/it,cpu:[56%],memory:[13809140K]
column:[Cabin] check [inverse type] complete,speed:[3.4ms]/it,cpu:[46%],memory:[13809248K]
column:[Embarked] check [inverse type] complete,speed:[3.68ms]/it,cpu:[41%],memory:[13808432K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[4.27ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[3.0ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[3.3ms]/it,cpu:[41%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[4.1ms]/it,cpu:[43%],memory:[4K]

In [12]:
nlp.transform(x_test[:5])

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,0.006943,-0.049788,0.094199,-0.016030,0.003412,0.131879,0.227311
501,0.001774,-1.027363,-0.072602,0.017521,-0.168437,-0.080284,0.188844,0.057639
502,0.001778,-1.035647,-0.074126,0.017324,-0.168437,-0.080284,0.188844,0.057639
503,0.001211,-0.985805,-0.123092,-0.009465,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,-0.968351,-0.120909,-0.007717,-0.233626,-0.181061,0.165193,0.226518

In [13]:
x_test_new.head(5)

,lsi_Name_0,lsi_Name_1,lsi_Name_2,lsi_Name_3,w2v_Name_0,w2v_Name_1,w2v_Name_2,w2v_Name_3
500,0.985461,0.006943,-0.049788,0.094199,-0.016030,0.003412,0.131879,0.227311
501,0.001774,-1.027363,-0.072602,0.017521,-0.168437,-0.080284,0.188844,0.057639
502,0.001778,-1.035647,-0.074126,0.017324,-0.168437,-0.080284,0.188844,0.057639
503,0.001211,-0.985805,-0.123092,-0.009465,-0.233626,-0.181061,0.165193,0.226518
504,0.001197,-0.968351,-0.120909,-0.007717,-0.233626,-0.181061,0.165193,0.226518