In [1]:
import os
os.chdir("../../")#与easymlops同级目录

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo2.csv",encoding="gbk")
data.head(5)

   label                                             review
0      1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1      1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2      1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3      1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4      1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风

In [3]:
data.shape

(7766, 2)

In [4]:
x=data[["review"]]
y=data["label"]

x_train=x[:7000]
x_test=x[7000:]
y_train=y[:7000]
y_test=y[7000:]

del data,x,y

### 训练

In [5]:
from easymlops import NLPPipeline
from easymlops.table.preprocessing import *
from easymlops.nlp.preprocessing import *
from easymlops.nlp.text_classification import TextCNNClassification,TextRNNClassification,HANClassification

In [6]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa(cols=["review"]))\
   .pipe(Lower())\
   .pipe(ExtractChineseWords())\
   .pipe(ExtractJieBaWords())\
   .pipe(VocabIndex())\
   .pipe(TextCNNClassification(y=y_train,col="review"))

x_test_new=nlp.fit(x_train).transform(x_test)
x_test_new.head(5)

             1         0
7000  0.011766  0.988234
7001  0.683056  0.316944
7002  0.910810  0.089190
7003  0.002599  0.997401
7004  0.085628  0.914372

In [12]:
# nlp=NLPPipeline()
# nlp.pipe(FixInput())\
#    .pipe(FillNa(cols=["review"]))\
#    .pipe(Lower())\
#    .pipe(ExtractJieBaWordsWithSentSplit())\
#    .pipe(VocabIndexWithSentSplit())\
#    .pipe(HANClassification(y=y_train,col="review"))

# x_test_new=nlp.fit(x_train).transform(x_test)
# x_test_new.head(5)

In [7]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ExtractChineseWords'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.ExtractJieBaWords'>) module check [transform] complete,speed:[1.88ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.VocabIndex'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.text_classification.textcnn.TextCNNClassification'>) module check [transform] complete,speed:[1.4ms]/it,cpu:[100%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[review] check [null value] complete,speed:[2.43ms]/it,cpu:[100%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[review] check [extreme value] complete,speed:[2.05ms]/it,cpu:[100%],memory:[5856384K]
column:[__all__] check [extreme value] complete,speed:[2.25ms]/it,cpu:[100%],memory:[5856384K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[review] check [inverse type] complete,speed:[2.47ms]/it,cpu:[100%],memory:[5856488K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################

### 持久化

In [8]:
nlp.save("ml.pkl")

In [10]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa())\
   .pipe(Lower())\
   .pipe(ExtractChineseWords())\
   .pipe(ExtractJieBaWords())\
   .pipe(VocabIndex())\
   .pipe(TextCNNClassification())

nlp.load("ml.pkl")

In [11]:
nlp.transform(x_test[:5])

             1         0
7000  0.011766  0.988234
7001  0.683056  0.316944
7002  0.910810  0.089190
7003  0.002599  0.997401
7004  0.085628  0.914372

In [13]:
x_test[:5]

                                                 review
7000  隔音效果非常差,基本上隔壁房间的说话声都能听到.最后一天隔壁老早起来吵架,简直就是对着你在说...
7001  房间隔音极差,邻房说话声音清晰可闻,任何杂音清晰入耳,提供的设施品质极差,电熨斗品质不佳还得...
7002  千万别去，虽然员工很尽心，但先天条及不足。在齐市没住过好酒店。我看还是试试如家吧。免费注册网...
7003  在酒店住的时候环境相当的差，卫生不打扫，前台服务态度相当的差，（个别的）还有那个保健中心的服...
7004  今年的5.1、10.1长假分别定了西安与重庆的如家，非常失望，如家简直无诚信可言。这里把我的...