In [1]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# 拆分训练测试
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

In [3]:
from easymlops import TablePipeLine
from easymlops.table.strategy import LGBMRegressionLayers
from easymlops.table.preprocessing import *
from easymlops.table.encoding import *
from easymlops.table.decomposition import *
from easymlops.table.classification import *
from easymlops.table.ensemble import *
from easymlops.table.strategy import FactorStrategy

In [4]:
table = TablePipeLine()
table.pipe(FixInput()) \
  .pipe(FillNa()) \
  .pipe(Parallel([OneHotEncoding(cols=["Pclass", "Sex"]), LabelEncoding(cols=["Sex", "Pclass"]),
                    TargetEncoding(cols=["Name", "Ticket", "Embarked", "Cabin", "Sex"], y=y_train)]))\
  .pipe(FillNa())\
  .pipe(FactorStrategy(y=y_train,ruler_feature_num=2))
table.fit(x_train)

In [5]:
table.transform(x_test).head(5)

,0,1,2,3,4,5,6,7,8,9,...,126,127,128,129,130,131,132,133,134,135
500,1,1,3,3,7,1,1,3,3,1,...,1,0,0,3,0,0,0,4,1,1
501,1,1,2,2,7,1,1,2,3,1,...,1,0,1,3,0,0,0,4,1,0
502,1,1,2,2,7,1,1,2,1,1,...,1,0,1,0,0,0,0,4,1,0
503,1,1,2,2,7,1,1,2,5,1,...,1,0,1,3,0,0,0,4,1,1
504,2,0,0,1,4,0,0,1,0,0,...,0,0,1,3,0,0,0,1,0,1

In [6]:
table[-1].show_detail().head()

              factor  tree_index  leaf_index              leaf_describe
0  Pclass_3,Pclass_1           0           0  Pclass_3<0.0|Pclass_1<0.0
1  Pclass_3,Pclass_1           0           1               0.0<Pclass_3
2  Pclass_3,Pclass_1           0           2  Pclass_3<0.0|0.0<Pclass_1
3  Pclass_3,Pclass_2           1           0  Pclass_3<0.0|Pclass_2<0.0
4  Pclass_3,Pclass_2           1           1               0.0<Pclass_3

In [7]:
# table[-1].ruler_totals

In [8]:
table.transform_single(x_test.to_dict("records")[0])

{0: 1,
 1: 1,
 2: 3,
 3: 3,
 4: 7,
 5: 1,
 6: 1,
 7: 3,
 8: 3,
 9: 1,
 10: 1,
 11: 1,
 12: 4,
 13: 2,
 14: 2,
 15: 0,
 16: 1,
 17: 0,
 18: 5,
 19: 1,
 20: 0,
 21: 0,
 22: 4,
 23: 0,
 24: 0,
 25: 0,
 26: 4,
 27: 1,
 28: 2,
 29: 1,
 30: 0,
 31: 2,
 32: 1,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 4,
 40: 1,
 41: 1,
 42: 1,
 43: 6,
 44: 5,
 45: 1,
 46: 1,
 47: 5,
 48: 1,
 49: 1,
 50: 1,
 51: 4,
 52: 2,
 53: 3,
 54: 6,
 55: 5,
 56: 0,
 57: 0,
 58: 5,
 59: 0,
 60: 0,
 61: 0,
 62: 4,
 63: 2,
 64: 3,
 65: 7,
 66: 2,
 67: 6,
 68: 2,
 69: 3,
 70: 3,
 71: 2,
 72: 5,
 73: 2,
 74: 4,
 75: 1,
 76: 5,
 77: 4,
 78: 1,
 79: 1,
 80: 1,
 81: 4,
 82: 2,
 83: 2,
 84: 0,
 85: 3,
 86: 0,
 87: 0,
 88: 0,
 89: 4,
 90: 1,
 91: 1,
 92: 5,
 93: 0,
 94: 0,
 95: 0,
 96: 4,
 97: 2,
 98: 3,
 99: 0,
 100: 0,
 101: 3,
 102: 4,
 103: 4,
 104: 3,
 105: 0,
 106: 0,
 107: 4,
 108: 1,
 109: 1,
 110: 0,
 111: 5,
 112: 1,
 113: 1,
 114: 4,
 115: 1,
 116: 1,
 117: 5,
 118: 3,
 119: 2,
 120: 1,
 121: 0,
 122: 0,
 123: 1,
 124: 0,
 125: 2,
 126: 1,
 127: 0,
 128: 0,
 129: 3,
 130: 0,
 131: 0,
 132: 0,
 133: 4,
 134: 1,
 135: 1}

In [9]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.8ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.strategy.factor_strategy.FactorStrategy'>) module check [transform] complete,speed:[12.58ms]/it,cpu:[100%],memory:[408K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[14.53ms]/it,cpu:[100%],memory:[292K]
column:[Pclass] check [null value] complete,speed:[14.79ms]/it,cpu:[100%],memory:[60K]
column:[Name] check [null value] complete,speed:[12.4ms]/it,cpu:[60%],memory:[944K]
column:[Sex] check [null value] complete,speed:[10.05ms]/it,cpu:[54%],memory:[0K]
column:[Age] check [null value] complete,speed:[8.64ms]/it,cpu:[72%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[9.69ms]/it,cpu:[58%],memory:[2176K]
column:[Parch] check [null value] complete,speed:[9.63ms]/it,cpu:[69%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[9.74ms]/it,cpu:[65%],memory:[0K]
column:[Fare] check [null value] complete,speed:[9.91ms]/it,cpu:[70%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[10.24ms]/it,cpu:[66%],memory:[14756K]
column:[Embarked] check [null value] complete,speed:[10.0ms]/it,cpu:[76%],memory:[1516K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[9.37ms]/it,cpu:[79%],memory:[83772K]
column:[Pclass] check [extreme value] complete,speed:[8.97ms]/it,cpu:[79%],memory:[17344K]
column:[Name] check [extreme value] complete,speed:[10.18ms]/it,cpu:[77%],memory:[25896K]
column:[Sex] check [extreme value] complete,speed:[10.01ms]/it,cpu:[76%],memory:[88392K]
column:[Age] check [extreme value] complete,speed:[10.07ms]/it,cpu:[77%],memory:[110256K]
column:[SibSp] check [extreme value] complete,speed:[9.64ms]/it,cpu:[77%],memory:[25028K]
column:[Parch] check [extreme value] complete,speed:[10.04ms]/it,cpu:[76%],memory:[28852K]
column:[Ticket] check [extreme value] complete,speed:[9.48ms]/it,cpu:[87%],memory:[25104K]
column:[Fare] check [extreme value] complete,speed:[10.06ms]/it,cpu:[79%],memory:[85460K]
column:[Cabin] check [extreme value] complete,speed:[9.84ms]/it,cpu:[71%],memory:[32360K]
column:[Embarked] check [extreme value] complete,speed:[9.91ms]/it,cpu:[77%],memory:[28504K]
column:[__all__] check [extreme value] complete,speed:[8.33ms]/it,cpu:[94%],memory:[28652K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[9.02ms]/it,cpu:[80%],memory:[16136K]
column:[Pclass] check [inverse type] complete,speed:[9.44ms]/it,cpu:[80%],memory:[3640K]
column:[Name] check [inverse type] complete,speed:[9.45ms]/it,cpu:[69%],memory:[12920K]
column:[Sex] check [inverse type] complete,speed:[8.88ms]/it,cpu:[76%],memory:[24000K]
column:[Age] check [inverse type] complete,speed:[9.48ms]/it,cpu:[76%],memory:[9036K]
column:[SibSp] check [inverse type] complete,speed:[9.84ms]/it,cpu:[81%],memory:[21788K]
column:[Parch] check [inverse type] complete,speed:[9.89ms]/it,cpu:[96%],memory:[32484K]
column:[Ticket] check [inverse type] complete,speed:[9.0ms]/it,cpu:[77%],memory:[18220K]
column:[Fare] check [inverse type] complete,speed:[9.78ms]/it,cpu:[74%],memory:[15124K]
column:[Cabin] check [inverse type] complete,speed:[9.77ms]/it,cpu:[76%],memory:[23012K]
column:[Embarked] check [inverse type] complete,speed:[11.59ms]/it,cpu:[82%],memory:[234548K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[10.12ms]/it,cpu:[65%],memory:[620K]
column:[Pclass] check [int trans float] complete,speed:[8.48ms]/it,cpu:[57%],memory:[4712K]
column:[SibSp] check [int trans float] complete,speed:[8.54ms]/it,cpu:[61%],memory:[204K]
column:[Parch] check [int trans float] complete,speed:[11.16ms]/it,cpu:[75%],memory:[11876K]

In [10]:
table.save("demo.pkl")

In [11]:
new_table=TablePipeLine()
new_table.load("demo.pkl")

In [12]:
table.transform(x_test).head(5)

,0,1,2,3,4,5,6,7,8,9,...,126,127,128,129,130,131,132,133,134,135
500,1,1,3,3,7,1,1,3,3,1,...,1,0,0,3,0,0,0,4,1,1
501,1,1,2,2,7,1,1,2,3,1,...,1,0,1,3,0,0,0,4,1,0
502,1,1,2,2,7,1,1,2,1,1,...,1,0,1,0,0,0,0,4,1,0
503,1,1,2,2,7,1,1,2,5,1,...,1,0,1,3,0,0,0,4,1,1
504,2,0,0,1,4,0,0,1,0,0,...,0,0,1,3,0,0,0,1,0,1

In [13]:
table.transform_single(x_test.to_dict("records")[0])

{0: 1,
 1: 1,
 2: 3,
 3: 3,
 4: 7,
 5: 1,
 6: 1,
 7: 3,
 8: 3,
 9: 1,
 10: 1,
 11: 1,
 12: 4,
 13: 2,
 14: 2,
 15: 0,
 16: 1,
 17: 0,
 18: 5,
 19: 1,
 20: 0,
 21: 0,
 22: 4,
 23: 0,
 24: 0,
 25: 0,
 26: 4,
 27: 1,
 28: 2,
 29: 1,
 30: 0,
 31: 2,
 32: 1,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 4,
 40: 1,
 41: 1,
 42: 1,
 43: 6,
 44: 5,
 45: 1,
 46: 1,
 47: 5,
 48: 1,
 49: 1,
 50: 1,
 51: 4,
 52: 2,
 53: 3,
 54: 6,
 55: 5,
 56: 0,
 57: 0,
 58: 5,
 59: 0,
 60: 0,
 61: 0,
 62: 4,
 63: 2,
 64: 3,
 65: 7,
 66: 2,
 67: 6,
 68: 2,
 69: 3,
 70: 3,
 71: 2,
 72: 5,
 73: 2,
 74: 4,
 75: 1,
 76: 5,
 77: 4,
 78: 1,
 79: 1,
 80: 1,
 81: 4,
 82: 2,
 83: 2,
 84: 0,
 85: 3,
 86: 0,
 87: 0,
 88: 0,
 89: 4,
 90: 1,
 91: 1,
 92: 5,
 93: 0,
 94: 0,
 95: 0,
 96: 4,
 97: 2,
 98: 3,
 99: 0,
 100: 0,
 101: 3,
 102: 4,
 103: 4,
 104: 3,
 105: 0,
 106: 0,
 107: 4,
 108: 1,
 109: 1,
 110: 0,
 111: 5,
 112: 1,
 113: 1,
 114: 4,
 115: 1,
 116: 1,
 117: 5,
 118: 3,
 119: 2,
 120: 1,
 121: 0,
 122: 0,
 123: 1,
 124: 0,
 125: 2,
 126: 1,
 127: 0,
 128: 0,
 129: 3,
 130: 0,
 131: 0,
 132: 0,
 133: 4,
 134: 1,
 135: 1}

In [14]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.strategy.factor_strategy.FactorStrategy'>) module check [transform] complete,speed:[9.6ms]/it,cpu:[81%],memory:[8436K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[9.79ms]/it,cpu:[80%],memory:[2292K]
column:[Pclass] check [null value] complete,speed:[9.52ms]/it,cpu:[54%],memory:[1704K]
column:[Name] check [null value] complete,speed:[10.18ms]/it,cpu:[76%],memory:[12040K]
column:[Sex] check [null value] complete,speed:[9.76ms]/it,cpu:[66%],memory:[9236K]
column:[Age] check [null value] complete,speed:[10.01ms]/it,cpu:[63%],memory:[16K]
column:[SibSp] check [null value] complete,speed:[9.74ms]/it,cpu:[70%],memory:[9016K]
column:[Parch] check [null value] complete,speed:[9.73ms]/it,cpu:[95%],memory:[2012K]
column:[Ticket] check [null value] complete,speed:[10.11ms]/it,cpu:[61%],memory:[8192K]
column:[Fare] check [null value] complete,speed:[9.74ms]/it,cpu:[77%],memory:[2532K]
column:[Cabin] check [null value] complete,speed:[9.85ms]/it,cpu:[59%],memory:[616K]
column:[Embarked] check [null value] complete,speed:[9.66ms]/it,cpu:[61%],memory:[92K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[10.32ms]/it,cpu:[83%],memory:[33052K]
column:[Pclass] check [extreme value] complete,speed:[9.94ms]/it,cpu:[74%],memory:[23748K]
column:[Name] check [extreme value] complete,speed:[9.95ms]/it,cpu:[92%],memory:[9268K]
column:[Sex] check [extreme value] complete,speed:[10.07ms]/it,cpu:[91%],memory:[208444K]
column:[Age] check [extreme value] complete,speed:[10.23ms]/it,cpu:[86%],memory:[151208K]
column:[SibSp] check [extreme value] complete,speed:[9.63ms]/it,cpu:[81%],memory:[40668K]
column:[Parch] check [extreme value] complete,speed:[9.23ms]/it,cpu:[74%],memory:[62276K]
column:[Ticket] check [extreme value] complete,speed:[9.13ms]/it,cpu:[72%],memory:[19800K]
column:[Fare] check [extreme value] complete,speed:[8.9ms]/it,cpu:[73%],memory:[700K]
column:[Cabin] check [extreme value] complete,speed:[9.09ms]/it,cpu:[73%],memory:[1660K]
column:[Embarked] check [extreme value] complete,speed:[9.24ms]/it,cpu:[79%],memory:[1012K]
column:[__all__] check [extreme value] complete,speed:[9.08ms]/it,cpu:[80%],memory:[123944K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[9.8ms]/it,cpu:[75%],memory:[36640K]
column:[Pclass] check [inverse type] complete,speed:[10.12ms]/it,cpu:[67%],memory:[34240K]
column:[Name] check [inverse type] complete,speed:[10.13ms]/it,cpu:[80%],memory:[46848K]
column:[Sex] check [inverse type] complete,speed:[9.83ms]/it,cpu:[70%],memory:[44692K]
column:[Age] check [inverse type] complete,speed:[9.59ms]/it,cpu:[69%],memory:[34924K]
column:[SibSp] check [inverse type] complete,speed:[10.16ms]/it,cpu:[70%],memory:[34164K]
column:[Parch] check [inverse type] complete,speed:[10.13ms]/it,cpu:[72%],memory:[35036K]
column:[Ticket] check [inverse type] complete,speed:[10.38ms]/it,cpu:[82%],memory:[35348K]
column:[Fare] check [inverse type] complete,speed:[10.18ms]/it,cpu:[77%],memory:[140148K]
column:[Cabin] check [inverse type] complete,speed:[9.43ms]/it,cpu:[82%],memory:[20632K]
column:[Embarked] check [inverse type] complete,speed:[10.1ms]/it,cpu:[69%],memory:[54768K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[8.22ms]/it,cpu:[67%],memory:[1192K]
column:[Pclass] check [int trans float] complete,speed:[9.33ms]/it,cpu:[51%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[7.14ms]/it,cpu:[50%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[7.88ms]/it,cpu:[72%],memory:[0K]

### 测试used_tree_index

In [15]:
table[-1].update_used_tree_index([2,3,5])

In [16]:
table.transform_single(x_test.to_dict("records")[0])

{2: 3, 3: 3, 5: 1}

In [17]:
table.transform(x_test)

     2  3  5
500  3  3  1
501  2  2  1
502  2  2  1
503  2  2  1
504  0  1  0
..  .. .. ..
886  1  0  2
887  0  1  0
888  2  2  1
889  1  0  0
890  3  3  1

[391 rows x 3 columns]

In [18]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[1.53ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.11ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.strategy.factor_strategy.FactorStrategy'>) module check [transform] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[1.8ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[1.79ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [null value] complete,speed:[2.1ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[2.05ms]/it,cpu:[90%],memory:[0K]
column:[Age] check [null value] complete,speed:[1.83ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[2.08ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [null value] complete,speed:[1.89ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[1.83ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[1.95ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[1.71ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[1.85ms]/it,cpu:[0%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[1.76ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [extreme value] complete,speed:[1.83ms]/it,cpu:[87%],memory:[11779124K]
column:[Name] check [extreme value] complete,speed:[1.86ms]/it,cpu:[100%],memory:[11776340K]
column:[Sex] check [extreme value] complete,speed:[1.95ms]/it,cpu:[94%],memory:[11771040K]
column:[Age] check [extreme value] complete,speed:[1.65ms]/it,cpu:[90%],memory:[11769176K]
column:[SibSp] check [extreme value] complete,speed:[1.91ms]/it,cpu:[90%],memory:[11767892K]
column:[Parch] check [extreme value] complete,speed:[1.96ms]/it,cpu:[82%],memory:[11766032K]
column:[Ticket] check [extreme value] complete,speed:[1.56ms]/it,cpu:[89%],memory:[11765860K]
column:[Fare] check [extreme value] complete,speed:[1.83ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [extreme value] complete,speed:[1.7ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [extreme value] complete,speed:[1.86ms]/it,cpu:[0%],memory:[0K]
column:[__all__] check [extreme value] complete,speed:[1.88ms]/it,cpu:[92%],memory:[11766040K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[1.93ms]/it,cpu:[89%],memory:[11763744K]
column:[Pclass] check [inverse type] complete,speed:[1.84ms]/it,cpu:[90%],memory:[11765108K]
column:[Name] check [inverse type] complete,speed:[2.15ms]/it,cpu:[92%],memory:[11763304K]
column:[Sex] check [inverse type] complete,speed:[1.9ms]/it,cpu:[90%],memory:[11764584K]
column:[Age] check [inverse type] complete,speed:[1.94ms]/it,cpu:[90%],memory:[11766468K]
column:[SibSp] check [inverse type] complete,speed:[2.0ms]/it,cpu:[91%],memory:[11766400K]
column:[Parch] check [inverse type] complete,speed:[2.22ms]/it,cpu:[90%],memory:[11765980K]
column:[Ticket] check [inverse type] complete,speed:[1.81ms]/it,cpu:[92%],memory:[11766360K]
column:[Fare] check [inverse type] complete,speed:[1.83ms]/it,cpu:[89%],memory:[11765536K]
column:[Cabin] check [inverse type] complete,speed:[1.54ms]/it,cpu:[91%],memory:[11766684K]
column:[Embarked] check [inverse type] complete,speed:[1.62ms]/it,cpu:[91%],memory:[11767452K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[1.89ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[0.57ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[1.61ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[1.96ms]/it,cpu:[0%],memory:[0K]

In [19]:
table.save("demo.pkl")

In [20]:
new_table=TablePipeLine()
new_table.load("demo.pkl")

In [21]:
table.transform(x_test).head(5)

     2  3  5
500  3  3  1
501  2  2  1
502  2  2  1
503  2  2  1
504  0  1  0

In [22]:
table.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.1ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.strategy.factor_strategy.FactorStrategy'>) module check [transform] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[1.87ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[1.71ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [null value] complete,speed:[1.84ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [null value] complete,speed:[1.57ms]/it,cpu:[0%],memory:[0K]
column:[Age] check [null value] complete,speed:[2.02ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [null value] complete,speed:[1.58ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [null value] complete,speed:[1.86ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [null value] complete,speed:[1.6ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [null value] complete,speed:[1.76ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [null value] complete,speed:[1.75ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [null value] complete,speed:[1.8ms]/it,cpu:[0%],memory:[0K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[1.92ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [extreme value] complete,speed:[1.53ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [extreme value] complete,speed:[1.75ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [extreme value] complete,speed:[1.85ms]/it,cpu:[0%],memory:[0K]
column:[Age] check [extreme value] complete,speed:[1.53ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [extreme value] complete,speed:[1.82ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [extreme value] complete,speed:[1.91ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [extreme value] complete,speed:[1.78ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [extreme value] complete,speed:[2.22ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [extreme value] complete,speed:[1.69ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [extreme value] complete,speed:[1.6ms]/it,cpu:[0%],memory:[0K]
column:[__all__] check [extreme value] complete,speed:[1.97ms]/it,cpu:[0%],memory:[0K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[1.84ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [inverse type] complete,speed:[1.78ms]/it,cpu:[0%],memory:[0K]
column:[Name] check [inverse type] complete,speed:[1.69ms]/it,cpu:[0%],memory:[0K]
column:[Sex] check [inverse type] complete,speed:[1.8ms]/it,cpu:[0%],memory:[0K]
column:[Age] check [inverse type] complete,speed:[1.89ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [inverse type] complete,speed:[1.43ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [inverse type] complete,speed:[1.38ms]/it,cpu:[0%],memory:[0K]
column:[Ticket] check [inverse type] complete,speed:[1.77ms]/it,cpu:[0%],memory:[0K]
column:[Fare] check [inverse type] complete,speed:[1.84ms]/it,cpu:[0%],memory:[0K]
column:[Cabin] check [inverse type] complete,speed:[1.65ms]/it,cpu:[0%],memory:[0K]
column:[Embarked] check [inverse type] complete,speed:[1.81ms]/it,cpu:[0%],memory:[0K]

############################################
 5.int数据转float测试:check_int_trans_float
############################################
column:[PassengerId] check [int trans float] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]
column:[Pclass] check [int trans float] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]
column:[SibSp] check [int trans float] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]
column:[Parch] check [int trans float] complete,speed:[1.56ms]/it,cpu:[0%],memory:[0K]